### ISSUE TITLE
Faceted heatmap's should share single colorbar

### ISSUE THREAD

**Issue by jonmmease** [plotly/plotly_express#1]
In this example...
![screen shot 2019-01-03 at 8 15 05 am](https://user-images.githubusercontent.com/15064365/50639530-cab12f80-0f2f-11e9-9f9a-8af2ab4462df.png)

each of the three heatmap traces is producing it's own colorbar with slightly different autorange extents, and they all overlap.  I think instead we should only display a single colorbar, and we should manually compute the `cmin` `cmax` values across the full dataset so that the colors across the three facets are comparable.

**Comment by nicolaskruchten** [comment]
I agree with you on what should happen, of course! Unfortunately I don't think this is something `px` can handle, at least not the computation of the bounds. We need some way of telling the JS layer that the color scale should be shared, so that it can handle the bounds computation itself, as it depends on the `z` parameter for each trace.

**Comment by nicolaskruchten** [comment]
UPDATE: we did in fact implement both [density heatmaps](https://plotly.com/python/2D-Histogram/) and [matrix heatmaps](https://plotly.com/python/heatmaps/) in Plotly Express.
