### ISSUE TITLE
Add distribution plot (distplot)

### ISSUE THREAD

**Issue by GitAnalyst** [plotly/plotly_express#100]
Currently, plotly_express is lacking _distplot_ from [plotly library](https://plot.ly/python/distplot/), is it planned for implementation? Distribution plot is handy for those who work in Data Science but most of Python visualization libraries do not support it (probably only Seaborn and Plotly). It would also be useful to include a parameter to disable interactivity when plotting a large number of data points (this would be useful for other plots as well).

**Comment by nicolaskruchten** [comment]
Thanks for the feedback!

The Plotly Express equivalent of Seaborn's `distplot` is `px.histogram()`, which has support for e.g. `marginal='rug'` and various `barmode` options. It's not exactly the same but I would be interested in hearing which specific differences are important and why :)

Re disabling interaction, the upcoming renderer framework in Plotly.py will allow for static rendering inline, but in the meantime, you can assign the output of any PX function and save as a static image using `plotly.io` as documented here: https://plot.ly/python/static-image-export/

**Comment by GitAnalyst** [comment]
Thanks for the answer. So, I've tried out `px.histogram()` and it is very useful for plotting histograms, but:
- `distplot` adds a curve (kernel density estimation or normal curve). Histograms by categories tend to overlap, and I know that `px.histogram()` provides many parameters to overcome that (`opacity`, `facet_row`, `facet_col`, `barmode`), but sometimes all you need is one clean plot comparing curves. Having the ability to turn on distplot, histogram and rug creates freedom to present what you want and `px.histogram()` is very near that.
- Regarding static plots, thanks for suggestion. My concern is more with plotly's `distplot`. I noticed that if you are not careful with for example `bin_size` parameter (which is sensitive to feature scale), then you can get out of ram pretty quick, because it will try to plot enormous amount of bins. I don't know if this can also be an issue with `px.histogram()`, because it uses a safer `nbins` parameter. I suppose if I wanted to visualize millions of data points with `plotly_express` I would want to make them static, because interactive plots are hungrier for computational resources. Nevertheless, `plotly_express` is really amazing at bringing a similar usage simplicity like Seaborn, but with superior Plotly's visuals. I moved to Python from R where `ggplot2` library is very handy and I find most of the visualization libraries in Python to be either ugly or impractical.

**Comment by nicolaskruchten** [comment]
Thanks for the response!

1. Plotly.js doesn't today offer curve-computation and Plotly Express isn't designed to do math at the Python level, so for now the figure-factory `displot` in Plotly is the way to go if that's what you need. This may change in a future version of Plotly.js/Plotly Express.
2. When using `px.histogram()` the default number of bins should be such that interactivity is not a problem, however data volumes themselves might be problematic because the binning is done client-side in Javascript and not server-side in Python. Again here the approach in the existing distplot implementation might be better for such a use-case, so long as you disable the rug marginal, which requires all the points.
