### ISSUE TITLE
Plotting with a for loop

### ISSUE THREAD

**Issue by robroc** [plotly/plotly_express#144]
I'm trying to produce multiple line plots, one for each column in my data, by looping over the columns. Nothing gets displayed in Jupyter Lab. Is this possible to do?

Python 3.6
Jupyter Lab 1.0.2
plotly==4.0.0
plotly-express==0.4.0

Code sample:

```stats = ['acousticness', 'danceability', 'energy','instrumentalness']
for stat in stats:
    px.line(data, x = 'sequence', y = stat, color = 'category', height= 200, title = stat)

**Comment by nicolaskruchten** [comment]
Short answer: add `.show()` to the end of the call.

Long answer: `px.<whatever>()` functions return a `Figure` object. If this function call happens to be the final call in a Jupyter cell, then the figure will display itself, otherwise it's "just another object". To force the figure to display itself, call `.show()` on it.

Longer answer: there's a long doc page about this here https://plot.ly/python/renderers/

happy plotting!

**Comment by nicolaskruchten** [comment]
PS I strongly recommend upgrading to `plotly` version 4.1.1 as there's a nasty bug in 4.0.0

**Comment by robroc** [comment]
Worked like a charm. Thanks for the quick help!
