### ISSUE TITLE
module 'plotly.graph_objs' has no attribute 'Splom'?

### ISSUE THREAD

**Issue by kcerva** [plotly/plotly_express#40]
I'm using data with a structure that is similar to the gapminder example, but get the following error:
module 'plotly.graph_objs' has no attribute 'Splom'. I get the same error if I try using the gapminder dataset.

**Comment by nicolaskruchten** [comment]
Sorry you're having trouble! Which version of `plotly` do you have installed?

**Comment by kcerva** [comment]
Plotly ver 2.2.3

**Comment by nicolaskruchten** [comment]
Ah that's why! `plotly_express` depends on `plotly>=3.7.1` today, and in general will tend to depend on the very latest version as new releases come out, given that features are being added to plotly.js/plotly.py specifically to support plotly express features :)

Out of curiosity, how did you install `plotly_express` such that you were not prompted to upgrade `plotly`?

**Comment by kcerva** [comment]
Oh I realised I hadn't updated the Jupyter Notebook I was working on... Sorry, my bad! I'm surprised it didn't send me an error about the library instead, though... Thanks for your help!

**Comment by nicolaskruchten** [comment]
OK, glad it's working!
